---
name: Upstream Issue Checker

on: push


permissions:
  contents: write

jobs:
  build-indico-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Install Depdencies
        run: |
          sudo apt install -y --install-recommends libxslt1-dev libxml2-dev libffi-dev libpcre3-dev \
              libyaml-dev build-essential libpq-dev libjpeg-turbo8-dev zlib1g-dev

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin

      - name: Clone indico
        run: git clone https://github.com/indico/indico.git indico-src --depth 1 --branch master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: indico-src/package-lock.json

      - name: npm ci
        working-directory: ./indico-src
        run: npm ci

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip

      - name: pip indico
        working-directory: ./indico-src
        run: pip install -e '.[dev]'

      - name: pip plugin
        working-directory: ./plugin
        run: pip install -e .
           
      - name: Build wheel
        working-directory: ./indico-src
        run: ./bin/maintenance/build-wheel.py plugin ../plugin

      - name: Upload Wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: indico-src/dist/*.whl

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: indico-src/dist/*.whl
